### ISSUE TITLE
Issue trying to include in Laravel 8 Project

### ISSUE THREAD

**Issue by Rotario** [duncan3dc/dusk#15]
Hi,
Just looking to use this for some basic automation tasks.
Getting a conflict with composer like so:
Problem 1
    - Installation request for phpunit/phpunit (locked at 9.4.1, required as ^9.3) -> satisfiable by phpunit/phpunit[9.4.1].
    - duncan3dc/dusk 1.0.0 requires phpunit/phpunit ^7.1 || ^8.0 -> satisfiable by phpunit/phpunit[8.5.x-dev].
    - duncan3dc/dusk 1.0.1 requires phpunit/phpunit ^7.1 || ^8.0 -> satisfiable by phpunit/phpunit[8.5.x-dev].
    - duncan3dc/dusk 1.0.2 requires phpunit/phpunit ^8.0 -> satisfiable by phpunit/phpunit[8.5.x-dev].
    - Conclusion: don't install phpunit/phpunit 8.5.x-dev
    - Installation request for duncan3dc/dusk ^1.0 -> satisfiable by duncan3dc/dusk[1.0.0, 1.0.1, 1.0.2].

I guess the phpUnit version needs updating in packagist?
Thanks

**Comment by KristianI** [comment]
duncan3dc's dusk is a standalone package for other projects (non-laravel projects).

You can install Dusk to Laravel 8 by running

```
composer require --dev laravel/dusk
```

**Comment by Rotario** [comment]
Ah fair enough! I was actually using it for production usage (not testing but web automation) and had to just copy a local folder over with updated dependencies - but thanks!
