### ISSUE TITLE
Support for PHP 8 & Laravel 9

### ISSUE THREAD

**Issue by Nawv** [duncan3dc/dusk#16]
PHP 7.4 is [out of active support](https://www.php.net/supported-versions.php), and will stop receiving security support in November this year. This project is also quite backdated on the version of Dusk it supports - currently V5, while Laravel V9 just dropped.

@duncan3dc Do you have any plans to update this project?

**Comment by duncan3dc** [comment]
Hi @Nawv, yes I plan to get back up to date with current releases soon, I'll leave this issue open until I do

**Comment by duncan3dc** [comment]
I've just released version [1.1.0](https://github.com/duncan3dc/dusk/releases/tag/1.1.0) which supports PHP 8 and works with Dusk V6 (Laravel V6-9)
