### ISSUE TITLE
Assert not found

### ISSUE THREAD

**Issue by daviddarke** [duncan3dc/dusk#5]
Hi there, using the script below:

```
<?php
use duncan3dc\Laravel\Dusk;

require __DIR__ . "/vendor/autoload.php";

$dusk = new Dusk;

$dusk->visit("http://example.com")
               ->assertPathIs('/home');
```

Gives me `PHP Fatal error:  Uncaught Error: Class 'PHPUnit\Framework\Assert' not found`.

Something like:

```
<?php
use duncan3dc\Laravel\Dusk;

require __DIR__ . "/vendor/autoload.php";

$dusk = new Dusk;

$dusk->visit("http://example.com");
echo $dusk->element("h1")->getText() . "\n";
```

Works fine though

**Comment by duncan3dc** [comment]
Hi @daviddarke, it looks like upstream doesn't declare PHPUnit as a dependency, so it's not installed.

If you do `composer require phpunit/phpunit` that should resolve it for you.

I've submit a [PR](https://github.com/laravel/dusk/pull/503) upstream to see if they'll resolve the issue there, if not I'll put a fix in here for it

**Comment by duncan3dc** [comment]
For some reason upstream have refused to declare their dependencies, so I've added one here to ensure `phpunit` is installed for you in [0.7.1](https://github.com/duncan3dc/dusk/releases/tag/0.7.1)

**Comment by daviddarke** [comment]
Great work! 😄
