### ISSUE TITLE
Using this to test a craft cms project. How to format results?

### ISSUE THREAD

**Issue by sunscreem** [duncan3dc/dusk#8]
Thank you for taking the time to make and share this project. SUPER helpful as I've a craft cms project that, at present, doesn't seem to have a nice framework for testing in place. I'm thinking of using this as a stop-gap.  

I tried installing php-unit but struggled as I'm so used to the out-of-box experience that Laravel provides.

I've managed to get it all working now, but I'm running my tests via just calling `php tests/exampleTest.php`. The output is odd though - if the test passes I see nothing. If it fails it throws a little bit of a weird message.

I wonder if you've come up with a way to make the output look as nice as the Laravel team have done?

Also - I'm curious how you would set up a folder structure for the browsers tests? 

What I'm getting at is - is there an example of this on a simple project anywhere that I can look at?

**Comment by duncan3dc** [comment]
Hi @sunscreem, if you've written tests using PHPUnit, and you've installed PHPUnit using `composer`, then you should be able to run your tests like so:
```php
vendor/bin/phpunit tests/exampleTest.php
```
Does that give you the output you're expecting?

**Comment by sunscreem** [comment]
Thanks Duncan - sort of... I'm getting a new error now. Hoping this stacktrace means something to you 😂:

```
$ vendor/bin/phpunit tests/exampleTest.php

DevTools listening on ws://127.0.0.1:12125/devtools/browser/637c5d68-3f00-428d-83d6-c61f152c029c
PHP Fatal error:  Uncaught PHPUnit\Runner\Exception: Class 'tests/exampleTest' could not be found in 'C:\www\icota\tests\exampleTest.php'. in C:\www\icota\vendor\phpunit\phpunit\src\Runner\StandardTestSuiteLoader.php:102
Stack trace:
#0 C:\www\icota\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(130): PHPUnit\Runner\StandardTestSuiteLoader->load('tests/exampleTe...', 'C:\\www\\icota\\te...')
#1 C:\www\icota\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(73): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('tests/exampleTe...', 'C:\\www\\icota\\te...')
#2 C:\www\icota\vendor\phpunit\phpunit\src\TextUI\Command.php(169): PHPUnit\Runner\BaseTestRunner->getTest('tests/exampleTe...', 'C:\\www\\icota\\te...', Array)
#3 C:\www\icota\vendor\phpunit\phpunit\src\TextUI\Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#4 C:\www\icota\vendor\phpunit\phpunit\phpunit(53): PHPUnit\TextUI\Command::main()
#5 {main}
  thrown in C:\www\icota\vendor\phpunit\phpunit\src\Runner\StandardTestSuiteLoader.php on line 102

Fatal error: Uncaught PHPUnit\Runner\Exception: Class 'tests/exampleTest' could not be found in 'C:\www\icota\tests\exampleTest.php'. in C:\www\icota\vendor\phpunit\phpunit\src\Runner\StandardTestSuiteLoader.php:102
Stack trace:
#0 C:\www\icota\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(130): PHPUnit\Runner\StandardTestSuiteLoader->load('tests/exampleTe...', 'C:\\www\\icota\\te...')
#1 C:\www\icota\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(73): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('tests/exampleTe...', 'C:\\www\\icota\\te...')
#2 C:\www\icota\vendor\phpunit\phpunit\src\TextUI\Command.php(169): PHPUnit\Runner\BaseTestRunner->getTest('tests/exampleTe...', 'C:\\www\\icota\\te...', Array)
#3 C:\www\icota\vendor\phpunit\phpunit\src\TextUI\Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#4 C:\www\icota\vendor\phpunit\phpunit\phpunit(53): PHPUnit\TextUI\Command::main()
#5 {main}
  thrown in C:\www\icota\vendor\phpunit\phpunit\src\Runner\StandardTestSuiteLoader.php on line 102
```

Here's my `tests/exampleTest.php`

```
<?php

use duncan3dc\Laravel\Dusk;

require __DIR__ . "/../vendor/autoload.php";

$dusk = new Dusk;

$dusk->visit("http://icota.test/") // the local project url
    ->assertPathIs('/');
```

**Comment by duncan3dc** [comment]
You'll need to write your tests in classes, here's a link to the PHPUnit getting started documentation:
https://phpunit.de/getting-started/phpunit-7.html

You can look at this repository for an example:
* [.phpunit.xml.dist](https://github.com/duncan3dc/dusk/blob/60e1742948caf6be974da9bc01ef742372d997a5/phpunit.xml.dist) to configure the PHPUnit settings, the `<filter>` is for code coverage so you won't need that, but you will need to tell PHPUnit where to load the bootstrap from.
* [bootstrap.php](https://github.com/duncan3dc/dusk/blob/60e1742948caf6be974da9bc01ef742372d997a5/tests/bootstrap.php) is very simple, basically just includes the composer autoloader, you could set this directory in you `.phpunit.xml.dist` but I prefer to have a clearly defined bootstrap for the unit tests.
* [DuskTest.php](https://github.com/duncan3dc/dusk/blob/60e1742948caf6be974da9bc01ef742372d997a5/tests/DuskTest.php) is an example PHPUnit test class, although this might be a bit confusing as it's testing the internals of Dusk.
Here's a stripped back version:
```php
<?php

namespace duncan3dc\LaravelTests;

use duncan3dc\Laravel\Dusk;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    public function testCanReachTheInternet()
    {
        $dusk = new Dusk();

        $dusk->visit("https://en.wikipedia.org/wiki/Example.com");

        $title = $dusk->element("h1")->getAttribute("innerHTML");
        $this->assertSame("example.com", $title);
    }
}
```

**Comment by sunscreem** [comment]
Amazing - thank you again for taking the time! I'll get dug in. 

Hugely appreciate it.
